version: '3.8'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://tester:password@db:5432/test

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./data_base_seeding/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test

volumes:
  postgres_data:
